name: dev_infrastructure

services:
  postgres_db:
    container_name: postgres
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=localpass
      - POSTGRES_DB=warehouse
    ports:
      - "5432:5432"